# kind: Pod 
# apiVersion: v1 
# metadata: 
#   name: pod-is-my-name 
#   labels: 
#     version: v1 
#     zone: prod 
# spec: 
#   containers: 
#   - name: hello-pod
#     image: nigelpoulton/k8sbook:1.0
#     ports: 
#     - containerPort: 8080  

# --- 
kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: deployment-is-my-name 
  labels: 
    version: v1 
    zone: prod 
spec: 
  replicas: 10 
  revisionHistoryLimit: 5 
  progressDeadlineSeconds: 300
  minReadySeconds: 10

  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 

  selector: 
    matchLabels: 
      version: v1 
      zone: prod 

  template: 
    metadata: 
      name: pod-is-my-name 
      labels: 
        version: v1 
        zone: prod 
    spec: 
      containers: 
      - name: hello-pod
        image: nigelpoulton/k8sbook:1.0
        ports: 
        - containerPort: 8080  
  
 