apiVersion: v1
kind: Pod 
metadata: 
  name: first-pod 
  labels: 
    version: v1
    zone: dev 
spec: 
  containers: 
  - name: first-container 
    image: nigelpoulton/k8sbook:1.0 
    ports: 
    - containerPort: 8080 