apiVersion: v1  # <api-group>/<version>
kind: Pod 
metadata: 
  name: hello-pod
  labels: 
    version: v1
    zone: prod
spec: 
  containers: 
  - name: hello-ctr
    image: nigelpoulton/k8sbook:1.0 
    ports: 
    - containerPort: 8080 