apiVersion: v1
kind: Service
metadata:
  name: k8sbook
spec:
  selector:
    app: initializer
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1 
kind: Pod 
metadata: 
  name: init-pod-pratice 
  labels: 
    zone: prod 
    version: v1 
spec: 
  initContainers: 
  - name: init-ctr 
    image: busybox 
    command: ['sh', '-c', 'until nslookup k8sbook; do echo waiting for k8sbook service;\
    sleep 1; done; echo Service found!']
  containers:
  - name: web-ctr
    image: nigelpoulton/web-app:1.0
    ports:
    - containerPort: 8080
